- project:
    templates:
      - check-requirements
      - lib-forward-testing
      - lib-forward-testing-python3
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python36-jobs
      - openstack-python37-jobs
      - periodic-stable-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-tox-functional
        - openstack-tox-functional-py35
        - tempest-full-py3-profiler-enabled
    gate:
      jobs:
        - openstack-tox-functional
        - openstack-tox-functional-py35
        - tempest-full-py3-profiler-enabled

- job:
    name: tempest-full-py3-profiler-enabled
    parent: tempest-full-py3
    voting: false
    post-run: playbooks/osprofiler-post.yaml
    description: |
      Run full tempest on py3 with profiling enabled
    required-projects:
      - openstack/osprofiler
    vars:
      tox_envlist: smoke
      devstack_localrc:
        OSPROFILER_COLLECTOR: redis
        OSPROFILER_HMAC_KEYS: SECRET_KEY
      devstack_plugins:
        osprofiler: https://git.openstack.org/openstack/osprofiler
